version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/test"
    target-branch: "pre-release"
    groups:
      unit-tests:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "pre-release"
    groups:
      gh-actions:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
