codecov:
  branch: "pre-release"
  require_ci_to_pass: yes
coverage:
  precision: 2
  round: nearest
  range: "80...100"
  status:
    patch:
      default:
        base: auto
        target: auto
        threshold: 5%
        if_ci_failed: error
        only_pulls: false
comment:
  layout: "header, condensed_files, condensed_footer"
  require_changes: true
  hide_project_coverage: true
